### ISSUE TITLE
Feedback on "add new hike" and UI

### ISSUE THREAD

**Issue by darxsky** [Luca-Tamburo/se-2022-12-HikeTracker#4]
As a local guide,
I should be able to add a gpx file when insert a new hike. In yours project, in the add page, there was a button for insert a gpx file but, at the demonstration, it didn’t work. While, for the positive aspect, I have seen a good and organized UI.

**Comment by Luca-Tamburo** [comment]
We provided the gpx file when adding a new hike and now it works.
Thanks for the report.
