### ISSUE TITLE
Restriction on filters (HT-1)

### ISSUE THREAD

**Issue by gdb-99** [Luca-Tamburo/se-2022-12-HikeTracker#6]
As a visitor, I want to see the available hikes by using filters. 
Some filters (such as _ascent_ or _length_) are restricted with static ranges; I would like to have more freedom of choice (ex. _length_ from 5 km to 12 km, where "5" and "12" are written by the visitor).
Other than that, the UI is really appealing to see.

**Comment by Luca-Tamburo** [comment]
We listened to the feedback and implemented this feature. Thank you very much for the report.
