### ISSUE TITLE
GPX files (HT-2) 

### ISSUE THREAD

**Issue by wrooklyn** [Luca-Tamburo/se-2022-12-HikeTracker#7]
As a local guide I would like to know if by uploading a gpx file, the data inside the file will be managed or not. For instance, if inside the gpx file there's data that's requested by the form when adding a new hike, will this data be inserted automatically in these fields so as to facilitate the overall procedure?

The overall form seems to be pretty easy to use, especially the button which allows to add more reference points.

**Comment by Luca-Tamburo** [comment]
We implemented this function, during sprint #2.
Thank you for the feedback.
